version: '3.7'

services:
  ngrok:
    image: wernight/ngrok
    environment:
      NGROK_AUTH: <YOUR-NGROK_AUTH-KEY-FROM-ngrok.com>
      NGROK_DEBUG: 1
      NGROK_PORT: gradio:8888
    ports:
      - 4040:4040
    links:
      - gradio

  gradio:
    build:
      dockerfile: Dockerfile
    command: nvidia-smi
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    ports: 
      - 8888:8888